
spring.application.name=DEPARTMENT-SERVICE

spring.boot.message= "Welcome to Department Service"

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:department_db